Ignore cloned_instead_of_copied clippy lint
The .clippy.toml declares this crate's msrv as 1.31.0, so it is a Clippy
bug that this lint is triggering in the first place. Iterator::copied is
from Rust 1.36.

https://github.com/rust-lang/rust-clippy/issues/7127

    error: used `cloned` where `copied` could be used instead
      --> src/range.rs:62:29
       |
    62 |         bytes(*self).iter().cloned()
       |                             ^^^^^^ help: try: `copied`
       |
       = note: `-D clippy::cloned-instead-of-copied` implied by `-D clippy::pedantic`
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied